### ISSUE TITLE
parse_fasta function does not support multi-line sequences

### ISSUE THREAD

**Issue by kaczmarj** [p-koo/cipher#14]
The `parse_fasta` function assumes that each sequence takes up one line only, but that is not always the case. Sequences can span multiple lines. I have an [implementation here](https://github.com/kaczmarj/rotation-koo-lab/blob/310bdf589c59f4ef9ef8511a479e69925c4bbcf3/chip-seq-to-hdf5-dataset/chipseq_utils.py#L237-L277) that handles multiple lines correctly.

https://github.com/p-koo/cipher/blob/bbfaaf454eff4c700a0d6eaec50997a072c2e2ce/cipher/preprocess/wrangle.py#L178-L211

**Comment by p-koo** [comment]
Your implementation looks good. Submit a pull request to the newest version!
