### ISSUE TITLE
improve speed of one-hot encoding

### ISSUE THREAD

**Issue by kaczmarj** [p-koo/cipher#15]
I have an implementation to one-hot encode sequences that is 3x faster than the current implementation. 

https://github.com/kaczmarj/rotation-koo-lab/blob/310bdf589c59f4ef9ef8511a479e69925c4bbcf3/chip-seq-to-hdf5-dataset/chipseq_utils.py#L317-L363

This is the current implementation:

https://github.com/p-koo/cipher/blob/48b1dccdd42576b2bf556edbc7243a838d9deaf0/cipher/preprocess/singletask.py#L160-L226

My implementation does not strip or pad the sequences, but i can add that.

**Comment by p-koo** [comment]
Your implementation looks good. Submit a pull request to the newest version!
