### ISSUE TITLE
discuss behavior of enforce_constant_size

### ISSUE THREAD

**Issue by kaczmarj** [p-koo/cipher#17]
The function `enforce_constant_size` accepts a path to a bed file and writes a bed file. This feels more like command-line behavior, where input and output are files. I would suggest that this function should take in a pandas dataframe representation of a bed file, and it should return a modified dataframe. I suggest that the processing script that uses this function should take care of loading and saving files, if it is necessary.

I have an implementation of this here: https://github.com/kaczmarj/rotation-koo-lab/blob/310bdf589c59f4ef9ef8511a479e69925c4bbcf3/chip-seq-to-hdf5-dataset/chipseq_utils.py#L102-L132

https://github.com/p-koo/cipher/blob/bbfaaf454eff4c700a0d6eaec50997a072c2e2ce/cipher/preprocess/wrangle.py#L7

**Comment by p-koo** [comment]
The problem is then that you need another function from dataframe to bed file. The use case is that bedtools getfasta will use the modified bed file to extract sequences from the reference genome.
